#!/usr/bin/env bash
# One-time server setup for the recipes app. Run AS ROOT on the EC2 box:
#
#   sudo bash /home/ec2-user/recipes_flask/deploy/provision.sh
#
# Idempotent: safe to re-run. It does NOT obtain the TLS certificate — DNS has
# to resolve first. The script prints the certbot command to run once it does.
set -euo pipefail

APP=/home/ec2-user/recipes_flask
DOMAIN=recipes.dustincremascoli.com
ENVDIR=/etc/recipes

say() { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }

[[ $EUID -eq 0 ]] || { echo "run as root" >&2; exit 1; }
[[ -d $APP ]] || { echo "missing $APP — deploy the code first" >&2; exit 1; }

say "Python virtualenv"
if [[ ! -x $APP/.venv/bin/python ]]; then
  python3 -m venv "$APP/.venv"
fi
"$APP/.venv/bin/pip" install --quiet --upgrade pip
"$APP/.venv/bin/pip" install --quiet -r "$APP/requirements.txt"
chown -R ec2-user:ec2-user "$APP"

say "Secrets directory"
install -d -m 0750 -o root -g ec2-user "$ENVDIR"
if [[ ! -f $ENVDIR/recipes.env ]]; then
  SECRET=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
  cat > "$ENVDIR/recipes.env" <<EOF
# Generated by provision.sh. Set DB_PASSWORD below to the recipes_app password.
DATABASE_URL=postgresql+psycopg://recipes_app:CHANGE_ME@127.0.0.1:5432/recipes
SECRET_KEY=${SECRET}
FLASK_ENV=production
REGISTRATION_OPEN=1
SESSION_COOKIE_SECURE=1
EOF
  echo "  wrote $ENVDIR/recipes.env — set the database password in it"
else
  echo "  $ENVDIR/recipes.env exists, left alone"
fi
chown root:ec2-user "$ENVDIR/recipes.env"
chmod 0640 "$ENVDIR/recipes.env"

say "systemd unit"
install -m 0644 "$APP/deploy/recipes-web.service" /etc/systemd/system/recipes-web.service
systemctl daemon-reload
systemctl enable recipes-web

say "nginx include"
install -m 0644 "$APP/deploy/proxy_params_recipes.inc" /etc/nginx/proxy_params_recipes.inc
install -d -m 0755 /var/www/letsencrypt

# Before the certificate exists the TLS server block cannot load, so stand up
# an HTTP-only vhost. certbot rewrites this file when it issues the cert.
if [[ ! -f /etc/letsencrypt/live/$DOMAIN/fullchain.pem ]]; then
  say "No certificate yet — installing HTTP-only vhost"
  cat > /etc/nginx/conf.d/recipes.conf <<EOF
limit_req_zone \$binary_remote_addr zone=recipes_auth:10m rate=12r/m;
limit_req_zone \$binary_remote_addr zone=recipes_all:10m rate=120r/m;

upstream recipes_app { server unix:/run/recipes/recipes.sock fail_timeout=0; }

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ { root /var/www/letsencrypt; }

    location /static/ {
        alias $APP/static/;
        expires 30d;
        access_log off;
        try_files \$uri =404;
    }
    location = /health { proxy_pass http://recipes_app; access_log off; }
    location ~ ^/(login|register)\$ {
        limit_req zone=recipes_auth burst=5 nodelay;
        include /etc/nginx/proxy_params_recipes.inc;
    }
    location / {
        limit_req zone=recipes_all burst=40 nodelay;
        include /etc/nginx/proxy_params_recipes.inc;
    }
}
EOF
else
  say "Certificate present — installing full TLS vhost"
  install -m 0644 "$APP/deploy/nginx-recipes.conf" /etc/nginx/conf.d/recipes.conf
fi

nginx -t
systemctl reload nginx

say "Starting the app"
systemctl restart recipes-web
sleep 2
systemctl is-active recipes-web || {
  echo "service failed to start — journalctl -u recipes-web -n 40" >&2
  exit 1
}

say "Done."
if [[ ! -f /etc/letsencrypt/live/$DOMAIN/fullchain.pem ]]; then
  cat <<EOF

Next steps:
  1. Add a DNS A record:  $DOMAIN  ->  $(curl -s --max-time 5 ifconfig.me || echo '<this host IP>')
  2. Wait for it to resolve, then:
       sudo certbot --nginx -d $DOMAIN
  3. Re-run this script to install the hardened TLS vhost.

EOF
fi
